### ISSUE TITLE
Rebranding to Kentico Kontent

### ISSUE THREAD

**Issue by petrsvihlik** [rshackleton/rshackleton.co.uk#134]
Hi @rshackleton !
We've just renamed Kentico Cloud to [Kentico Kontent](https://kontent.ai/blog/moving-to-caas-with-kentico-kontent). We are in the process of renaming all SDKs, developer tools, and sample apps. Please consider renaming your plugin (code: namespaces, classes; repo, wiki, GH topics, etc.) to Kentico Kontent. See the guidelines at https://gitter.im/Kentico/Kontent?at=5d8b643d692d464f7969c6d9.

Thanks!

**Comment by rshackleton** [comment]
@petrsvihlik appreciate the update, I think any reference to Kentico Cloud in this repo is blocked by the upstream `gatsby-source-kentico-cloud` plugin.

I'm considering migrating to the custom source plugin I've developed temporarily though, that is using the Kontent brand though.

**Comment by petrsvihlik** [comment]
@Simply007 will be taking care of migrating the plugin very very soon. I'd suggest waiting for the official plugin.

https://github.com/Kentico/gatsby-source-kentico-cloud/issues/69

**Comment by rshackleton** [comment]
The official plugins lacks features at the moment so I'll be using my own until it's caught up :)

**Comment by petrsvihlik** [comment]
It's going to be soon 😀 stay tuned!

**Comment by rshackleton** [comment]
Forgot to close this, on the latest beta of the source plugin now :)
